### ISSUE TITLE
Use async throughout

### ISSUE THREAD

**Issue by karissa** [jayrbolton/dat-pki#12]
This library will probably be used in other applications and so should be async. There are some synchronous fs calls

**Comment by jayrbolton** [comment]
@karissa: Do y'all minimalists have a minimalistic lib for helping to manage async using only callbacks without promises or anything? eg it'd be cool to do such things as:
- run `[a, b, c]` in parallel and call `cb` when all our done 
- run `[a, b, c]` in sequence with each taking as input the callback result from the previous

**Comment by karissa** [comment]
Yes, in fact! run-parallel and run-series and run-waterfall

**Comment by jayrbolton** [comment]
I made everything async and with run-waterfall and run-parallel and stuck to the `callback(err, result)` convention. For example: https://github.com/jayrbolton/dat-pki/blob/master/lib/checkHandshake.js
