### ISSUE TITLE
Use sodium-universal instead of sodium-native

### ISSUE THREAD

**Issue by aschrijver** [jayrbolton/dat-pki#19]
Using `sodium-universal` makes it easier to use `dat-pki` in browser environments.

**Comment by jayrbolton** [comment]
:+1:

**Comment by jayrbolton** [comment]
I was using sodium-universal in lib/crypto.js but for some reason had not updated the package.json. 
https://github.com/jayrbolton/dat-pki/commit/0582f2016aa21f71cd401780e9aee37f09d563da
